### ISSUE TITLE
Visualization libraries

### ISSUE THREAD

**Issue by chaaals** [chaaals/da-project-frontend#3]
## Description
Look for visualization libraries to use in the project.

**Comment by chaaals** [comment]
D3.js
https://d3js.org/getting-started

**Comment by eklavyabytesquad** [comment]
Yeah D3 is powerful library when it comes to visualization and another is three.js for 3d visualization.

**Comment by eklavyabytesquad** [comment]
if you need any help you can tell me i will help 👍

**Comment by chaaals** [comment]
Using Flowbite + Apex Charts
https://flowbite.com/docs/plugins/charts/
